<?xml version="1.0" encoding="utf-8"?>
<Schema Namespace="ErrorModel" Alias="Self" annotation:UseStrongSpatialTypes="false" xmlns:annotation="http://schemas.microsoft.com/ado/2009/02/edm/annotation" xmlns:customannotation="http://schemas.microsoft.com/ado/2013/11/edm/customannotation" xmlns="http://schemas.microsoft.com/ado/2009/11/edm">
  <EntityType Name="ExceptionDetail">
    <Key>
      <PropertyRef Name="RowID" />
    </Key>
    <Property Name="RowID" Type="Int32" Nullable="false" annotation:StoreGeneratedPattern="Identity" />
    <Property Name="ExceptionDate" Type="DateTime" Nullable="false" Precision="3" />
    <Property Name="InnerException" Type="String" MaxLength="Max" FixedLength="false" Unicode="true" />
    <Property Name="StackTrace" Type="String" MaxLength="Max" FixedLength="false" Unicode="true" />
    <Property Name="Area" Type="String" MaxLength="Max" FixedLength="false" Unicode="true" />
    <Property Name="Message" Type="String" MaxLength="Max" FixedLength="false" Unicode="true" />
    <Property Name="User" Type="String" MaxLength="Max" FixedLength="false" Unicode="true" />
  </EntityType>
  <EntityContainer Name="ErrorDBContext" annotation:LazyLoadingEnabled="true">
    <EntitySet Name="ExceptionDetails" EntityType="Self.ExceptionDetail" />
  </EntityContainer>
</Schema>